/*********************************************************
       Code Generated By  .  .  .  .  Delaney's ScriptBot
       WWW .  .  .  .  .  .  .  .  .  www.scriptbot.io
       Template Name.  .  .  .  .  .  Project Green 3.0
       Template Version.  .  .  .  .  20220411 004
       Author .  .  .  .  .  .  .  .  Delaney

                      ,        ,--,_
                       \ _ ___/ /\|
                       ( )__, )
                      |/_  '--,
                        \ `  / '
 
 Note: Create this object,
       populate from properties from the Core.Domain classes
       and send to a view.

Object Models
-------------
What can this object do.

* GetIdea()
  Two overrides to get the parent idea for the object.
  This is used to display parent in a summary table.



* GetStage()
  Two overrides to get the parent stage for the object.
  This is used to display parent in a summary table.

* GetStages()
  Two overrides to get a list of alternative parent stages.* GetModels()
  Return a model containing properties populated with the objects values

* GetCreatedAndUpdated()
  Two overrides to get Users who created updated this object
  and assign them to CreatedBy and UpdatedBy properties.
 
 *********************************************************/

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SilkFlo.Web.Models.Business
{
    public partial class IdeaStage : Abstract
    {
        private SilkFlo.Data.Core.Domain.Business.IdeaStage _core;
        #region Constructors
        
        // This constructor is used by HTTP posts 
        public IdeaStage ()
        {
            _core = new SilkFlo.Data.Core.Domain.Business.IdeaStage();
        }
        public IdeaStage(SilkFlo.Data.Core.Domain.Business.IdeaStage core)
        {
            _core = core ??   
	        throw new NullReferenceException("The SilkFlo.Data.Core.Domain.Business.IdeaStage cannot be null");
        }
        #endregion

        #region Properties
        public string DisplayText { get; set; }
        public SilkFlo.Data.Core.Domain.Business.IdeaStage GetCore()
        {
            return _core;
        }
        public void SetCore(SilkFlo.Data.Core.Domain.Business.IdeaStage core)
        {
            _core = core;
        }

        public bool IsNew => string.IsNullOrWhiteSpace(Id);

        /// <summary>
        /// Primary Key
        /// </summary>
        #region Id
        [StringLength(255,
                      MinimumLength = 0,
                      ErrorMessage = "Id cannot be greater than 255 characters in length.")]
        [DisplayName("Id")]
        public string Id
        {
            get => _core.Id;
            set
            {
                if (_core.Id == value)
                    return;

                _core.Id = value;
            }
        }

        public string Id_Error { get; set; }
        public string Id_ErrorMessage { get; set; } = "Required";
        public bool Id_IsInValid { get; set; }
        #endregion

        #region Date End
        [DisplayName("Date End")]
        public DateTime? DateEnd
        {
            get => _core.DateEnd;
            set
            {
                if (_core.DateEnd == value)
                    return;

                _core.DateEnd = value;
            }
        }

        public string DateEnd_ErrorMessage { get; set; }
        public bool DateEnd_IsInValid { get; set; }
        #endregion

        #region Date End Estimate
        [DisplayName("Date End Estimate")]
        public DateTime? DateEndEstimate
        {
            get => _core.DateEndEstimate;
            set
            {
                if (_core.DateEndEstimate == value)
                    return;

                _core.DateEndEstimate = value;
            }
        }

        public string DateEndEstimate_ErrorMessage { get; set; }
        public bool DateEndEstimate_IsInValid { get; set; }
        #endregion

        #region Date Start
        [DisplayName("Date Start")]
        public DateTime? DateStart
        {
            get => _core.DateStart;
            set
            {
                if (_core.DateStart == value)
                    return;

                _core.DateStart = value;
            }
        }

        public string DateStart_ErrorMessage { get; set; }
        public bool DateStart_IsInValid { get; set; }
        #endregion

        #region Date Start Estimate
        [Required]
        [DisplayName("Date Start Estimate")]
        public DateTime DateStartEstimate
        {
            get => _core.DateStartEstimate;
            set
            {
                if (_core.DateStartEstimate == value)
                    return;

                _core.DateStartEstimate = value;
            }
        }

        public string DateStartEstimate_ErrorMessage { get; set; } = "Required";
        public bool DateStartEstimate_IsInValid { get; set; }
        #endregion

        #region Is In Work Flow?
        [Required]
        [DisplayName("Is In Work Flow?")]
        public bool IsInWorkFlow
        {
            get => _core.IsInWorkFlow;
            set
            {
                if (_core.IsInWorkFlow == value)
                    return;

                _core.IsInWorkFlow = value;
            }
        }

        public string IsInWorkFlow_ErrorMessage { get; set; } = "Required";
        public bool IsInWorkFlow_IsInValid { get; set; }
        #endregion

        [Required]
        [DisplayName("Idea")]
        public string IdeaId
        {
            get => _core.IdeaId;
            set
            {
                if (_core.IdeaId == value)
                    return;

                _core.IdeaId = value;
                _idea = null;
            }
        }
        private Models.Business.Idea _idea;
        public Models.Business.Idea Idea
        {
            get
            {
                if (_idea != null)
                    return _idea;

                if (_core.Idea != null)
                    _idea = new Models.Business.Idea(_core.Idea);

                return _idea;
            }
            set
            {
                if (_idea == value)
                    return;

                _idea = value;

                if (_idea == null)
                    _core.Idea = null;
                else
                {
                    if (_core.IdeaId != _idea.Id)
                        _core.Idea = _idea.GetCore();

                    _core.IdeaId = _idea.Id;
                }
            }
        }

        [DisplayName("Idea")]
        public string IdeaString => Idea?.ToString();

        public string IdeaId_ErrorMessage { get; set; } = "Required";
        public bool IdeaId_IsInValid { get; set; }

        [Required]
        [DisplayName("Stage")]
        public string StageId
        {
            get => _core.StageId;
            set
            {
                if (_core.StageId == value)
                    return;

                _core.StageId = value;
                _stage = null;
            }
        }
        private Models.Shared.Stage _stage;
        public Models.Shared.Stage Stage
        {
            get
            {
                if (_stage != null)
                    return _stage;

                if (_core.Stage != null)
                    _stage = new Models.Shared.Stage(_core.Stage);

                return _stage;
            }
            set
            {
                if (_stage == value)
                    return;

                _stage = value;

                if (_stage == null)
                    _core.Stage = null;
                else
                {
                    if (_core.StageId != _stage.Id)
                        _core.Stage = _stage.GetCore();

                    _core.StageId = _stage.Id;
                }
            }
        }

        [DisplayName("Stage")]
        public string StageString => Stage?.ToString();

        public string StageId_ErrorMessage { get; set; } = "Required";
        public bool StageId_IsInValid { get; set; }

        private List<Models.Business.Idea> _ideas;
        public List<Models.Business.Idea> Ideas
        {
            get => _ideas ??= new List<Models.Business.Idea>();
            set => _ideas = value;
        }

        private List<Models.Shared.Stage> _stages;
        public List<Models.Shared.Stage> Stages
        {
            get => _stages ??= new List<Models.Shared.Stage>();
            set => _stages = value;
        }

        private List<Models.Business.IdeaStageStatus> _ideaStageStatuses; 
        public List<Models.Business.IdeaStageStatus> IdeaStageStatuses 
        {
            get
            {
                if (_ideaStageStatuses != null)
                    return _ideaStageStatuses;

                _ideaStageStatuses = new List<Business.IdeaStageStatus>();

                if (_core.IdeaStageStatuses == null)
                    return _ideaStageStatuses;

                foreach (var core in _core.IdeaStageStatuses)
                    _ideaStageStatuses.Add(new Models.Business.IdeaStageStatus(core));

                return _ideaStageStatuses;
            }
            set => _ideaStageStatuses = value;
        }

        private List<Models.Business.ImplementationCost> _implementationCosts; 
        public List<Models.Business.ImplementationCost> ImplementationCosts 
        {
            get
            {
                if (_implementationCosts != null)
                    return _implementationCosts;

                _implementationCosts = new List<Business.ImplementationCost>();

                if (_core.ImplementationCosts == null)
                    return _implementationCosts;

                foreach (var core in _core.ImplementationCosts)
                    _implementationCosts.Add(new Models.Business.ImplementationCost(core));

                return _implementationCosts;
            }
            set => _implementationCosts = value;
        }

        #region OwnerId
        public string OwnerId => UpdatedById ?? CreatedById;
        #endregion

        #region Owner  
        public string Owner => UpdatedBy ?? CreatedBy;
        #endregion
        

        #region CreatedBy
        [DisplayName("Created By")]
        public string CreatedBy => _core.CreatedBy == null ? "" : _core.CreatedBy.ToString();
        #endregion

        #region CreatedDate
        [DisplayName("Created Date")]
        public DateTime? CreatedDate
        {
            get => _core.CreatedDate;
            set
            {
                if (_core.CreatedDate == value)
                    return;

                _core.CreatedDate = value;
            }
        }
        #endregion

        [DisplayName("Created Date")]
        public string CreatedDateString => CreatedDate?.ToString(Data.Core.Settings.DateFormatShort);

        #region CreatedById
        [DisplayName("Created By Id")]
        public string CreatedById
        {
            get => _core.CreatedById;
            set => _core.CreatedById = value;
        }
        #endregion

        #region UpdatedById
        [DisplayName("Updated By Id")]
        public string UpdatedById
        {
            get => _core.UpdatedById;
            set => _core.UpdatedById = value;
        }
        #endregion

        #region UpdatedBy
        [DisplayName("Updated By")]
        public string UpdatedBy => _core.UpdatedBy == null ? "" : _core.UpdatedBy.ToString();
        #endregion

        #region UpdatedDate
        [DisplayName("Updated Date")]
        public DateTime? UpdatedDate
        {
            get => _core.UpdatedDate;
            set
            {
                if (_core.UpdatedDate == value)
                    return;

                _core.UpdatedDate = value;
            }
        }
        #endregion

        [DisplayName("Updated Date")]
        public string UpdatedDateString => UpdatedDate?.ToString(Data.Core.Settings.DateTimeFormatShort);


        [DisplayName("Date")]
        public string DateDisplayed => UpdatedDate == null ? CreatedDate?.ToString("yyyy-MM-dd") : UpdatedDate?.ToString("yyyy-MM-dd");

        [DisplayName("Date Time")]
        public string DateTimeDisplayed => UpdatedDate == null ? CreatedDate?.ToString("yyyy-MM-dd HH:mm:ss") : UpdatedDate?.ToString("yyyy-MM-dd HH:mm:ss");
        #endregion

        #region IsDeleted
        [DisplayName("Is Deleted")]
        public bool IsDeleted
        {
            get => _core.IsDeleted;
            set
            {
                if (_core.IsDeleted == value)
                    return;

                _core.IsDeleted = value;
            }
        }
        #endregion

        #region IsSaved
        [DisplayName("Is Saved")]
        public bool IsSaved => _core.IsSaved;
        #endregion

        public async Task GetCreatedAndUpdated(Data.Core.IUnitOfWork unitOfWork)
        {
            _core.CreatedBy = await unitOfWork.Users.GetAsync(_core.CreatedById);
            _core.UpdatedBy = await unitOfWork.Users.GetAsync(_core.UpdatedById);
        }

        /// <summary>
        /// Check unique key constraints.
        /// </summary>
        /// <returns>ViewModels.Feedback</returns>
        public async Task<ViewModels.Feedback> CheckUniqueAsync(
        Data.Core.IUnitOfWork unitOfWork,
        ViewModels.Feedback feedback)
        {
            if (unitOfWork == null)
                throw new NullReferenceException("Data.Core.IUnitOfWork cannot be null");

            // Check unique
            var message = await Data.Persistence.UnitOfWork.IsUniqueAsync(GetCore());// Data.Persistence.UnitOfWork.IsUniqueAsync(GetCore());

            if (string.IsNullOrWhiteSpace(message)) 
                return feedback;


             // We have a conflict, give feedback.
            if (feedback.Elements.ContainsKey("DateStartEstimate"))
                feedback.Elements["DateStartEstimate"] = message;
            else
                feedback.Elements.Add("DateStartEstimate", message);

            if (feedback.Elements.ContainsKey("IdeaId"))
                feedback.Elements["IdeaId"] = message;
            else
                feedback.Elements.Add("IdeaId", message);

            if (feedback.Elements.ContainsKey("StageId"))
                feedback.Elements["StageId"] = message;
            else
                feedback.Elements.Add("StageId", message);


            feedback.IsValid = false;

            return feedback;
        }

        public static List<Models.Business.IdeaStage> Create(IEnumerable<Data.Core.Domain.Business.IdeaStage> cores)
        {
            return cores.Select(core => new Models.Business.IdeaStage(core)).ToList();
        }
        
        public static Models.Business.IdeaStage[] Create(Data.Core.Domain.Business.IdeaStage[] cores)
        {
            return cores.Select(core => new Models.Business.IdeaStage(core)).ToArray();
        }
    }
}