/*********************************************************
       Code Generated By  .  .  .  .  Delaney's ScriptBot
       WWW .  .  .  .  .  .  .  .  .  www.scriptbot.io
       Template Name.  .  .  .  .  .  Project Green 3.0
       Template Version.  .  .  .  .  20210407 014
       Author .  .  .  .  .  .  .  .  Delaney

                      ,        ,--,_
                       \ _ ___/ /\|
                       ( )__, )
                      |/_  '--,
                        \ `  / '

 *********************************************************/

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System;
using System.Threading.Tasks;
using SilkFlo.Data.Core;

namespace SilkFlo.Web.Controllers.Administration.Shop
{
    public partial class PriceController : Abstract
    {
        public PriceController(IUnitOfWork unitOfWork,
                                  Services.ViewToString viewToString,
                                  IAuthorizationService authorisation) : base(unitOfWork, viewToString, authorisation) { }


        [HttpGet("/Administration/Shop/Price")]
        [Authorize(Policy = Policy.Administrator)]
        public async Task<IActionResult> Index()
        {
            try
            {
                IEnumerable<Data.Core.Domain.Shop.Price> cores;

                cores = (await _unitOfWork.ShopPrices
                                         .GetAllAsync())
                                         .ToArray();

                await _unitOfWork.ShopCurrencies.GetCurrencyForAsync(cores);
                await _unitOfWork.SharedPeriods.GetPeriodForAsync(cores);
                await _unitOfWork.ShopProducts.GetProductForAsync(cores);

                var models = new List<Models.Shop.Price>();

                if(cores != null)
                {
                    cores = cores.OrderBy(m => m.Period?.ToString())
                                 .ThenBy(m => m.Product?.ToString());

                    foreach(var core in cores)
                    {
                        var model = new Models.Shop.Price(core);
                        models.Add(model);
                    }
                }

                var summary = new Models.Summary<Models.Shop.Price>
                {
                    Models = models,
                    Count = models.Count,
                };

                return View("/Views/Administration/Shop/Price/Index.cshtml", summary);
            }
            catch (Exception ex)
            {
                _unitOfWork.Log(ex);

                var summary = new Models.Summary<Models.Shop.Price>
                {
                    Models = null,
                    Count = 0,
                };

                ModelState.AddModelError(
                        "Error",
                        Models.Log.Message_DatabaseErrorFetchList);

                return View("/Views/Administration/Shop/Price/Index.cshtml", summary);
            }
        }
        [HttpGet("/Administration/Shop/Price/Delete/{id}")]
        [Authorize(Policy = Policy.Administrator)]
        public async Task<IActionResult> Delete (string id)
        {
            if (id == null)
                return Redirect("/Administration/shop/price");

            var price = await _unitOfWork.ShopPrices.GetAsync(id);

            if (price == null)
                return Redirect("/Administration/Shop/Price");
            else
            {
                await _unitOfWork.ShopCurrencies.GetCurrencyForAsync(price);
                await _unitOfWork.SharedPeriods.GetPeriodForAsync(price);
                await _unitOfWork.ShopProducts.GetProductForAsync(price);

                if (price.CreatedById != null)
                    price.CreatedBy = await _unitOfWork.Users.GetAsync(price.CreatedById);

                if (price.UpdatedById != null)
                    price.UpdatedBy = await _unitOfWork.Users.GetAsync(price.UpdatedById);

                var model = new Models.Shop.Price(price);

                return View("/Views/Administration/Shop/Price/delete.cshtml", model);
            }
        }
        [HttpPost("/Administration/Shop/Price/Delete")]
        [Authorize(Policy = Policy.Administrator)]
        public async Task<IActionResult> Delete(Models.Shop.Price model)
        {
            if (model == null)
                return Redirect("/Administration/Shop/Price");


            var userId = GetUserId();

            if (userId == null)
            {
                ModelState.AddModelError("Error",
                                         "UserId is missing.");

                return View("/Views/Administration/Shop/Price/Delete.cshtml", model);
            }


            if (model.Id == null)
            {
                var message = "[POST] The primary key ID is missing.";

                ModelState.AddModelError("Error",
                                         message);

                _unitOfWork.Log(message,
                                Severity.Warning);

                await _unitOfWork.CompleteAsync();

                return View("/Views/Administration/Shop/Price/Delete.cshtml", model);
            }


            try
            {
                await _unitOfWork.ShopPrices
                                 .RemoveAsync(model.Id);

                await _unitOfWork.CompleteAsync();

                return Redirect(
                    "/Administration/Shop/Price");
            }
            catch (ChildDependencyException ex)
            {
                ModelState.AddModelError("Error",
                                         ex.Message);
                return View("/Views/Administration/Shop/Price/Delete.cshtml", model);
            }
            catch (NotFoundException ex)
            {
                ModelState.AddModelError("Error",
                                         ex.Message);
                return View("/Views/Administration/Shop/Price/Delete.cshtml", model);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error",
                                         "Cannot delete the Price.");

                _unitOfWork.Log(ex);
                await _unitOfWork.CompleteAsync();
                return View("/Views/Administration/Shop/Price/Delete.cshtml", model);
            }
        }

        [HttpGet("/Administration/Shop/Price/Edit/{id}")]
        [HttpGet("/Administration/Shop/Price/Edit")]
        [Authorize(Policy = Policy.Administrator)]
        public async Task<IActionResult> Edit(string id)
        {
            Data.Core.Domain.Shop.Price price;

            if (string.IsNullOrWhiteSpace(id))
            {
                price = new Data.Core.Domain.Shop.Price
                {
                    Id = Guid.NewGuid().ToString(),
                };
            }
            else
            {
                price = await _unitOfWork.ShopPrices.GetAsync(id);

                if (price == null)
                    return Redirect(
                        "/Administration/Shop/Price");
                await _unitOfWork.ShopCurrencies.GetCurrencyForAsync(price);
                await _unitOfWork.SharedPeriods.GetPeriodForAsync(price);
                await _unitOfWork.ShopProducts.GetProductForAsync(price);

            }

            var model = new Models.Shop.Price(price);
            await model.GetCreatedAndUpdated(_unitOfWork);

            var coreCurrencies = await _unitOfWork.ShopCurrencies.GetAllAsync();
            model.Currencies.Add(new Models.Shop.Currency{ DisplayText = "Select..." });
            model.Currencies.AddRange(Models.Shop.Currency.Create(coreCurrencies));
            var coreProducts = await _unitOfWork.ShopProducts.GetAllAsync();
            model.Products.AddRange(Models.Shop.Product.Create(coreProducts));

            return View("/Views/Administration/Shop/Price/Edit.cshtml", model);
        }


        [HttpPost("/Administration/Shop/Price/Edit")]
        [Authorize(Policy = Policy.Administrator)]
        public async Task<IActionResult> Edit(Models.Shop.Price model)
        {
            try
            {
                // Get the userId
                var userId = GetUserId();


                // Is the userId present.
                // If not return to view.                
                if (userId == null)
                {
                    ModelState.AddModelError(
                            "Error",
                            "userId is missing.");

                    return View("/Views/Administration/Shop/Price/Edit.cshtml", model);
                }


                // Is the model valid?
                // If not return to view.
                bool isValid = Validate(_unitOfWork, model);

                var feedback = new ViewModels.Feedback();
                feedback = await model.CheckUniqueAsync(_unitOfWork, feedback);
                if (!feedback.IsValid)
                {
                    isValid = false;
                    foreach (var feedbackElement in feedback.Elements)
                        model.Errors.Add(feedbackElement.Value);
                }

                if (!isValid)
                {
                    // Get parent: Shop.Currency -> Currency
                    await _unitOfWork.ShopCurrencies.GetCurrencyForAsync(model.GetCore());
                    model.Currency =
                        model.GetCore().Currency == null ?
                            null :
                            new Models.Shop.Currency(model.GetCore().Currency);


                    // Get parent: Shop.Product -> Product
                    await _unitOfWork.ShopProducts.GetProductForAsync(model.GetCore());
                    model.Product =
                        model.GetCore().Product == null ?
                            null :
                            new Models.Shop.Product(model.GetCore().Product);

                    // Get list of potential parents: Shop.Currency -> Currency
                    var coreCurrencies = await _unitOfWork.ShopCurrencies.GetAllAsync();
                    model.Currencies.Add(new Models.Shop.Currency{ DisplayText = "<Empty>" });
                    foreach (var core in coreCurrencies)
                        model.Currencies.Add(new Models.Shop.Currency(core));

                    // Get list of potential parents: Shop.Product -> Product
                    var coreProducts = await _unitOfWork.ShopProducts.GetAllAsync();
                    foreach (var core in coreProducts)
                        model.Products.Add(new Models.Shop.Product(core));


                    return View("/Views/Administration/Shop/Price/Edit.cshtml", model);
                }


                // Process the forms content.
                await _unitOfWork.ShopPrices.AddAsync(model.GetCore());


                if(await _unitOfWork.CompleteAsync() == DataStoreResult.Success)
                    return Redirect(
                        "/Administration/Shop/Price");

                return View("/Views/Administration/Shop/Price/Edit.cshtml", model);
            }
            catch (Exception ex)
            {
                _unitOfWork.Log(ex);

                ModelState.AddModelError(
                    "Error",
                    Models.Log.Message_CouldNotSave);

                return View("/Views/Administration/Shop/Price/Edit.cshtml", model);
            }
        }

        [HttpPost("/Administration/Shop/Price/Cancel")]
        public IActionResult Cancel()
        {
            return Redirect(
                "/Administration/Shop/Price");
        }
    }
}