/*********************************************************
       Code Generated By  .  .  .  .  Delaney's ScriptBot
       WWW .  .  .  .  .  .  .  .  .  www.scriptbot.io
       Template Name.  .  .  .  .  .  Project Green 3.0
       Template Version.  .  .  .  .  20220411 004
       Author .  .  .  .  .  .  .  .  Delaney

                      ,        ,--,_
                       \ _ ___/ /\|
                       ( )__, )
                      |/_  '--,
                        \ `  / '
 
 Note: Create this object,
       populate from properties from the Core.Domain classes
       and send to a view.

Object Models
-------------
What can this object do.

* GetStage()
  Two overrides to get the parent stage for the object.
  This is used to display parent in a summary table.

* GetStages()
  Two overrides to get a list of alternative parent stages.* GetModels()
  Return a model containing properties populated with the objects values

* GetCreatedAndUpdated()
  Two overrides to get Users who created updated this object
  and assign them to CreatedBy and UpdatedBy properties.
 
 *********************************************************/

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SilkFlo.Web.Models.Shared
{
    public partial class IdeaStatus : Abstract
    {
        private SilkFlo.Data.Core.Domain.Shared.IdeaStatus _core;
        #region Constructors
        
        // This constructor is used by HTTP posts 
        public IdeaStatus ()
        {
            _core = new SilkFlo.Data.Core.Domain.Shared.IdeaStatus();
        }
        public IdeaStatus(SilkFlo.Data.Core.Domain.Shared.IdeaStatus core)
        {
            _core = core ??   
	        throw new NullReferenceException("The SilkFlo.Data.Core.Domain.Shared.IdeaStatus cannot be null");
        }
        #endregion

        #region Properties
        private string _displayText;
        public string DisplayText
        { 
            get => string.IsNullOrWhiteSpace(_displayText) ? Name : _displayText;
            set => _displayText = value;
        }
        public SilkFlo.Data.Core.Domain.Shared.IdeaStatus GetCore()
        {
            return _core;
        }
        public void SetCore(SilkFlo.Data.Core.Domain.Shared.IdeaStatus core)
        {
            _core = core;
        }

        public bool IsNew => string.IsNullOrWhiteSpace(Id);

        /// <summary>
        /// Primary Key
        /// </summary>
        #region Id
        [StringLength(255,
                      MinimumLength = 0,
                      ErrorMessage = "Id cannot be greater than 255 characters in length.")]
        [DisplayName("Id")]
        public string Id
        {
            get => _core.Id;
            set
            {
                if (_core.Id == value)
                    return;

                _core.Id = value;
            }
        }

        public string Id_Error { get; set; }
        public string Id_ErrorMessage { get; set; } = "Required";
        public bool Id_IsInValid { get; set; }
        #endregion

        #region Button Class
        [Required]
        [StringLength(100,
                      ErrorMessage = "Button Class must be between 1 and 100 characters in length.")]
        [DisplayName("Button Class")]
        public string ButtonClass
        {
            get => _core.ButtonClass;
            set
            {
                if (_core.ButtonClass == value)
                    return;

                _core.ButtonClass = value;
            }
        }

        public string ButtonClass_ErrorMessage { get; set; } = "Required";
        public bool ButtonClass_IsInValid { get; set; }
        #endregion

        #region IsPathToSuccess
        [Required]
        [DisplayName("IsPathToSuccess")]
        public bool IsPathToSuccess
        {
            get => _core.IsPathToSuccess;
            set
            {
                if (_core.IsPathToSuccess == value)
                    return;

                _core.IsPathToSuccess = value;
            }
        }

        public string IsPathToSuccess_ErrorMessage { get; set; } = "Required";
        public bool IsPathToSuccess_IsInValid { get; set; }
        #endregion

        #region Name
        [Required]
        [StringLength(50,
                      ErrorMessage = "Name must be between 1 and 50 characters in length.")]
        [DisplayName("Name")]
        public string Name
        {
            get => _core.Name;
            set
            {
                if (_core.Name == value)
                    return;

                _core.Name = value;
            }
        }

        public string Name_ErrorMessage { get; set; } = "Required";
        public bool Name_IsInValid { get; set; }
        #endregion

        #region RequireIdeaStageField
        [Required]
        [DisplayName("RequireIdeaStageField")]
        public bool RequireIdeaStageField
        {
            get => _core.RequireIdeaStageField;
            set
            {
                if (_core.RequireIdeaStageField == value)
                    return;

                _core.RequireIdeaStageField = value;
            }
        }

        public string RequireIdeaStageField_ErrorMessage { get; set; } = "Required";
        public bool RequireIdeaStageField_IsInValid { get; set; }
        #endregion

        #region Sort
        [Required]
        [DisplayName("Sort")]
        public int Sort
        {
            get => _core.Sort;
            set
            {
                if (_core.Sort == value)
                    return;

                _core.Sort = value;
            }
        }

        public string Sort_ErrorMessage { get; set; } = "Required";
        public bool Sort_IsInValid { get; set; }
        #endregion

        #region Button Class
        [Required]
        [StringLength(100,
                      ErrorMessage = "Button Class must be between 1 and 100 characters in length.")]
        [DisplayName("Button Class")]
        public string TextClass
        {
            get => _core.TextClass;
            set
            {
                if (_core.TextClass == value)
                    return;

                _core.TextClass = value;
            }
        }

        public string TextClass_ErrorMessage { get; set; } = "Required";
        public bool TextClass_IsInValid { get; set; }
        #endregion

        [Required]
        [DisplayName("Stage")]
        public string StageId
        {
            get => _core.StageId;
            set
            {
                if (_core.StageId == value)
                    return;

                _core.StageId = value;
                _stage = null;
            }
        }
        private Models.Shared.Stage _stage;
        public Models.Shared.Stage Stage
        {
            get
            {
                if (_stage != null)
                    return _stage;

                if (_core.Stage != null)
                    _stage = new Models.Shared.Stage(_core.Stage);

                return _stage;
            }
            set
            {
                if (_stage == value)
                    return;

                _stage = value;

                if (_stage == null)
                    _core.Stage = null;
                else
                {
                    if (_core.StageId != _stage.Id)
                        _core.Stage = _stage.GetCore();

                    _core.StageId = _stage.Id;
                }
            }
        }

        [DisplayName("Stage")]
        public string StageString => Stage?.ToString();

        public string StageId_ErrorMessage { get; set; } = "Required";
        public bool StageId_IsInValid { get; set; }

        private List<Models.Shared.Stage> _stages;
        public List<Models.Shared.Stage> Stages
        {
            get => _stages ??= new List<Models.Shared.Stage>();
            set => _stages = value;
        }

        private List<Models.Business.IdeaStageStatus> _ideaStageStatuses; 
        public List<Models.Business.IdeaStageStatus> IdeaStageStatuses 
        {
            get
            {
                if (_ideaStageStatuses != null)
                    return _ideaStageStatuses;

                _ideaStageStatuses = new List<Business.IdeaStageStatus>();

                if (_core.IdeaStageStatuses == null)
                    return _ideaStageStatuses;

                foreach (var core in _core.IdeaStageStatuses)
                    _ideaStageStatuses.Add(new Models.Business.IdeaStageStatus(core));

                return _ideaStageStatuses;
            }
            set => _ideaStageStatuses = value;
        }

        #region OwnerId
        public string OwnerId => UpdatedById ?? CreatedById;
        #endregion

        #region Owner  
        public string Owner => UpdatedBy ?? CreatedBy;
        #endregion
        

        #region CreatedBy
        [DisplayName("Created By")]
        public string CreatedBy => _core.CreatedBy == null ? "" : _core.CreatedBy.ToString();
        #endregion

        #region CreatedDate
        [DisplayName("Created Date")]
        public DateTime? CreatedDate
        {
            get => _core.CreatedDate;
            set
            {
                if (_core.CreatedDate == value)
                    return;

                _core.CreatedDate = value;
            }
        }
        #endregion

        [DisplayName("Created Date")]
        public string CreatedDateString => CreatedDate?.ToString(Data.Core.Settings.DateFormatShort);

        #region CreatedById
        [DisplayName("Created By Id")]
        public string CreatedById
        {
            get => _core.CreatedById;
            set => _core.CreatedById = value;
        }
        #endregion

        #region UpdatedById
        [DisplayName("Updated By Id")]
        public string UpdatedById
        {
            get => _core.UpdatedById;
            set => _core.UpdatedById = value;
        }
        #endregion

        #region UpdatedBy
        [DisplayName("Updated By")]
        public string UpdatedBy => _core.UpdatedBy == null ? "" : _core.UpdatedBy.ToString();
        #endregion

        #region UpdatedDate
        [DisplayName("Updated Date")]
        public DateTime? UpdatedDate
        {
            get => _core.UpdatedDate;
            set
            {
                if (_core.UpdatedDate == value)
                    return;

                _core.UpdatedDate = value;
            }
        }
        #endregion

        [DisplayName("Updated Date")]
        public string UpdatedDateString => UpdatedDate?.ToString(Data.Core.Settings.DateTimeFormatShort);


        [DisplayName("Date")]
        public string DateDisplayed => UpdatedDate == null ? CreatedDate?.ToString("yyyy-MM-dd") : UpdatedDate?.ToString("yyyy-MM-dd");

        [DisplayName("Date Time")]
        public string DateTimeDisplayed => UpdatedDate == null ? CreatedDate?.ToString("yyyy-MM-dd HH:mm:ss") : UpdatedDate?.ToString("yyyy-MM-dd HH:mm:ss");
        #endregion

        #region IsDeleted
        [DisplayName("Is Deleted")]
        public bool IsDeleted
        {
            get => _core.IsDeleted;
            set
            {
                if (_core.IsDeleted == value)
                    return;

                _core.IsDeleted = value;
            }
        }
        #endregion

        #region IsSaved
        [DisplayName("Is Saved")]
        public bool IsSaved => _core.IsSaved;
        #endregion

        public async Task GetCreatedAndUpdated(Data.Core.IUnitOfWork unitOfWork)
        {
            _core.CreatedBy = await unitOfWork.Users.GetAsync(_core.CreatedById);
            _core.UpdatedBy = await unitOfWork.Users.GetAsync(_core.UpdatedById);
        }

        /// <summary>
        /// Check unique key constraints.
        /// </summary>
        /// <returns>ViewModels.Feedback</returns>
        public async Task<ViewModels.Feedback> CheckUniqueAsync(
        Data.Core.IUnitOfWork unitOfWork,
        ViewModels.Feedback feedback)
        {
            if (unitOfWork == null)
                throw new NullReferenceException("Data.Core.IUnitOfWork cannot be null");

            // Check unique
            var message = await Data.Persistence.UnitOfWork.IsUniqueAsync(GetCore());// Data.Persistence.UnitOfWork.IsUniqueAsync(GetCore());

            if (string.IsNullOrWhiteSpace(message)) 
                return feedback;


             // We have a conflict, give feedback.
            if (feedback.Elements.ContainsKey("Name"))
                feedback.Elements["Name"] = message;
            else
                feedback.Elements.Add("Name", message);

            if (feedback.Elements.ContainsKey("StageId"))
                feedback.Elements["StageId"] = message;
            else
                feedback.Elements.Add("StageId", message);


            feedback.IsValid = false;

            return feedback;
        }

        public override string ToString()
        {
            if(!string.IsNullOrWhiteSpace(DisplayText))
                return DisplayText;

            return Name;
        }
        public static List<Models.Shared.IdeaStatus> Create(IEnumerable<Data.Core.Domain.Shared.IdeaStatus> cores, bool includeEmpty = false)
        {
            if (cores == null)
                return null;

            if(includeEmpty)
            {
                var models = new List<Models.Shared.IdeaStatus>();
                models.Add(new Models.Shared.IdeaStatus
                {
                    DisplayText = "<Empty>"
                });

                models.AddRange(cores.Select(core => new Models.Shared.IdeaStatus(core)));
                return models;
            }

            return cores.Select(core => new Models.Shared.IdeaStatus(core)).ToList();
        }

        public static Models.Shared.IdeaStatus[] Create(Data.Core.Domain.Shared.IdeaStatus[] cores, bool includeEmpty = false)
        {
            if (cores == null)
                return null;

            if(includeEmpty)
                return Create(cores.ToList(), true).ToArray();

            return cores.Select(core => new Models.Shared.IdeaStatus(core)).ToArray();
        }
    }
}