/*********************************************************
       Code Generated By  .  .  .  .  Delaney's ScriptBot
       WWW .  .  .  .  .  .  .  .  .  www.scriptbot.io
       Template Name.  .  .  .  .  .  Project Green 3.0
       Template Version.  .  .  .  .  20210407 014
       Author .  .  .  .  .  .  .  .  Delaney

                      ,        ,--,_
                       \ _ ___/ /\|
                       ( )__, )
                      |/_  '--,
                        \ `  / '

 *********************************************************/

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System;
using System.Threading.Tasks;
using SilkFlo.Data.Core;

namespace SilkFlo.Web.Controllers.Administration.Business
{
    public partial class IdeaApplicationVersionController : Abstract
    {
        public IdeaApplicationVersionController(IUnitOfWork unitOfWork,
                                  Services.ViewToString viewToString,
                                  IAuthorizationService authorisation) : base(unitOfWork, viewToString, authorisation) { }


        [HttpGet("/Administration/Business/IdeaApplicationVersion")]
        [Authorize(Policy = Policy.Administrator)]
        public async Task<IActionResult> Index()
        {
            try
            {
                IEnumerable<Data.Core.Domain.Business.IdeaApplicationVersion> cores;

                cores = (await _unitOfWork.BusinessIdeaApplicationVersions
                                         .GetAllAsync())
                                         .ToArray();

                await _unitOfWork.BusinessIdeas.GetIdeaForAsync(cores);
                await _unitOfWork.SharedLanguages.GetLanguageForAsync(cores);
                await _unitOfWork.BusinessVersions.GetVersionForAsync(cores);

                var models = new List<Models.Business.IdeaApplicationVersion>();

                if(cores != null)
                {
                    foreach(var core in cores)
                    {
                        var model = new Models.Business.IdeaApplicationVersion(core);
                        models.Add(model);
                    }
                }

                var summary = new Models.Summary<Models.Business.IdeaApplicationVersion>
                {
                    Models = models,
                    Count = models.Count,
                };

                return View("/Views/Administration/Business/IdeaApplicationVersion/Index.cshtml", summary);
            }
            catch (Exception ex)
            {
                _unitOfWork.Log(ex);

                var summary = new Models.Summary<Models.Business.IdeaApplicationVersion>
                {
                    Models = null,
                    Count = 0,
                };

                ModelState.AddModelError(
                        "Error",
                        Models.Log.Message_DatabaseErrorFetchList);

                return View("/Views/Administration/Business/IdeaApplicationVersion/Index.cshtml", summary);
            }
        }
        [HttpGet("/Administration/Business/IdeaApplicationVersion/Delete/{id}")]
        [Authorize(Policy = Policy.Administrator)]
        public async Task<IActionResult> Delete (string id)
        {
            if (id == null)
                return Redirect("/Administration/business/ideaApplicationVersion");

            var ideaApplicationVersion = await _unitOfWork.BusinessIdeaApplicationVersions.GetAsync(id);

            if (ideaApplicationVersion == null)
                return Redirect("/Administration/Business/IdeaApplicationVersion");
            else
            {
                await _unitOfWork.BusinessIdeas.GetIdeaForAsync(ideaApplicationVersion);
                await _unitOfWork.SharedLanguages.GetLanguageForAsync(ideaApplicationVersion);
                await _unitOfWork.BusinessVersions.GetVersionForAsync(ideaApplicationVersion);

                if (ideaApplicationVersion.CreatedById != null)
                    ideaApplicationVersion.CreatedBy = await _unitOfWork.Users.GetAsync(ideaApplicationVersion.CreatedById);

                if (ideaApplicationVersion.UpdatedById != null)
                    ideaApplicationVersion.UpdatedBy = await _unitOfWork.Users.GetAsync(ideaApplicationVersion.UpdatedById);

                var model = new Models.Business.IdeaApplicationVersion(ideaApplicationVersion);

                return View("/Views/Administration/Business/IdeaApplicationVersion/delete.cshtml", model);
            }
        }
        [HttpPost("/Administration/Business/IdeaApplicationVersion/Delete")]
        [Authorize(Policy = Policy.Administrator)]
        public async Task<IActionResult> Delete(Models.Business.IdeaApplicationVersion model)
        {
            if (model == null)
                return Redirect("/Administration/Business/IdeaApplicationVersion");


            var userId = GetUserId();

            if (userId == null)
            {
                ModelState.AddModelError("Error",
                                         "UserId is missing.");

                return View("/Views/Administration/Business/IdeaApplicationVersion/Delete.cshtml", model);
            }


            if (model.Id == null)
            {
                var message = "[POST] The primary key ID is missing.";

                ModelState.AddModelError("Error",
                                         message);

                _unitOfWork.Log(message,
                                Severity.Warning);

                await _unitOfWork.CompleteAsync();

                return View("/Views/Administration/Business/IdeaApplicationVersion/Delete.cshtml", model);
            }


            try
            {
                await _unitOfWork.BusinessIdeaApplicationVersions
                                 .RemoveAsync(model.Id);

                await _unitOfWork.CompleteAsync();

                return Redirect(
                    "/Administration/Business/IdeaApplicationVersion");
            }
            catch (ChildDependencyException ex)
            {
                ModelState.AddModelError("Error",
                                         ex.Message);
                return View("/Views/Administration/Business/IdeaApplicationVersion/Delete.cshtml", model);
            }
            catch (NotFoundException ex)
            {
                ModelState.AddModelError("Error",
                                         ex.Message);
                return View("/Views/Administration/Business/IdeaApplicationVersion/Delete.cshtml", model);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error",
                                         "Cannot delete the IdeaApplicationVersion.");

                _unitOfWork.Log(ex);
                await _unitOfWork.CompleteAsync();
                return View("/Views/Administration/Business/IdeaApplicationVersion/Delete.cshtml", model);
            }
        }

        [HttpGet("/Administration/Business/IdeaApplicationVersion/Edit/{id}")]
        [HttpGet("/Administration/Business/IdeaApplicationVersion/Edit")]
        [Authorize(Policy = Policy.Administrator)]
        public async Task<IActionResult> Edit(string id)
        {
            Data.Core.Domain.Business.IdeaApplicationVersion ideaApplicationVersion;

            if (string.IsNullOrWhiteSpace(id))
            {
                ideaApplicationVersion = new Data.Core.Domain.Business.IdeaApplicationVersion
                {
                    Id = Guid.NewGuid().ToString(),
                };
            }
            else
            {
                ideaApplicationVersion = await _unitOfWork.BusinessIdeaApplicationVersions.GetAsync(id);

                if (ideaApplicationVersion == null)
                    return Redirect(
                        "/Administration/Business/IdeaApplicationVersion");
                await _unitOfWork.BusinessIdeas.GetIdeaForAsync(ideaApplicationVersion);
                await _unitOfWork.SharedLanguages.GetLanguageForAsync(ideaApplicationVersion);
                await _unitOfWork.BusinessVersions.GetVersionForAsync(ideaApplicationVersion);

            }

            var model = new Models.Business.IdeaApplicationVersion(ideaApplicationVersion);
            await model.GetCreatedAndUpdated(_unitOfWork);

            var coreLanguages = await _unitOfWork.SharedLanguages.GetAllAsync();
            model.Languages.AddRange(Models.Shared.Language.Create(coreLanguages));
            var coreVersions = await _unitOfWork.BusinessVersions.GetAllAsync();
            model.Versions.AddRange(Models.Business.Version.Create(coreVersions));

            return View("/Views/Administration/Business/IdeaApplicationVersion/Edit.cshtml", model);
        }


        [HttpPost("/Administration/Business/IdeaApplicationVersion/Edit")]
        [Authorize(Policy = Policy.Administrator)]
        public async Task<IActionResult> Edit(Models.Business.IdeaApplicationVersion model)
        {
            try
            {
                // Get the userId
                var userId = GetUserId();


                // Is the userId present.
                // If not return to view.                
                if (userId == null)
                {
                    ModelState.AddModelError(
                            "Error",
                            "userId is missing.");

                    return View("/Views/Administration/Business/IdeaApplicationVersion/Edit.cshtml", model);
                }


                // Is the model valid?
                // If not return to view.
                bool isValid = Validate(_unitOfWork, model);
                if (!isValid)
                {
                    // Get parent: Shared.Language -> Language
                    await _unitOfWork.SharedLanguages.GetLanguageForAsync(model.GetCore());
                    model.Language =
                        model.GetCore().Language == null ?
                            null :
                            new Models.Shared.Language(model.GetCore().Language);


                    // Get parent: Business.Version -> Version
                    await _unitOfWork.BusinessVersions.GetVersionForAsync(model.GetCore());
                    model.Version =
                        model.GetCore().Version == null ?
                            null :
                            new Models.Business.Version(model.GetCore().Version);

                    // Get list of potential parents: Shared.Language -> Language
                    var coreLanguages = await _unitOfWork.SharedLanguages.GetAllAsync();
                    foreach (var core in coreLanguages)
                        model.Languages.Add(new Models.Shared.Language(core));

                    // Get list of potential parents: Business.Version -> Version
                    var coreVersions = await _unitOfWork.BusinessVersions.GetAllAsync();
                    foreach (var core in coreVersions)
                        model.Versions.Add(new Models.Business.Version(core));


                    return View("/Views/Administration/Business/IdeaApplicationVersion/Edit.cshtml", model);
                }


                // Process the forms content.
                await _unitOfWork.BusinessIdeaApplicationVersions.AddAsync(model.GetCore());


                if(await _unitOfWork.CompleteAsync() == DataStoreResult.Success)
                    return Redirect(
                        "/Administration/Business/IdeaApplicationVersion");

                return View("/Views/Administration/Business/IdeaApplicationVersion/Edit.cshtml", model);
            }
            catch (Exception ex)
            {
                _unitOfWork.Log(ex);

                ModelState.AddModelError(
                    "Error",
                    Models.Log.Message_CouldNotSave);

                return View("/Views/Administration/Business/IdeaApplicationVersion/Edit.cshtml", model);
            }
        }

        [HttpPost("/Administration/Business/IdeaApplicationVersion/Cancel")]
        public IActionResult Cancel()
        {
            return Redirect(
                "/Administration/Business/IdeaApplicationVersion");
        }
    }
}