/*********************************************************
       Code Generated By  .  .  .  .  Delaney's ScriptBot
       WWW .  .  .  .  .  .  .  .  .  www.scriptbot.io
       Template Name.  .  .  .  .  .  Project Green 3.0
       Template Version.  .  .  .  .  20220411 004
       Author .  .  .  .  .  .  .  .  Delaney

                      ,        ,--,_
                       \ _ ___/ /\|
                       ( )__, )
                      |/_  '--,
                        \ `  / '
 
 Note: Create this object,
       populate from properties from the Core.Domain classes
       and send to a view.

Object Models
-------------
What can this object do.

* GetClients()
  Two overrides to get Clients children for this object.

* GetModels()
  Return a model containing properties populated with the objects values

* GetCreatedAndUpdated()
  Two overrides to get Users who created updated this object
  and assign them to CreatedBy and UpdatedBy properties.
 
 *********************************************************/

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SilkFlo.Web.Models.Shop
{
    public partial class Discount : Abstract
    {
        private SilkFlo.Data.Core.Domain.Shop.Discount _core;
        #region Constructors
        
        // This constructor is used by HTTP posts 
        public Discount ()
        {
            _core = new SilkFlo.Data.Core.Domain.Shop.Discount();
        }
        public Discount(SilkFlo.Data.Core.Domain.Shop.Discount core)
        {
            _core = core ??   
	        throw new NullReferenceException("The SilkFlo.Data.Core.Domain.Shop.Discount cannot be null");
        }
        #endregion

        #region Properties
        private string _displayText;
        public string DisplayText
        { 
            get => string.IsNullOrWhiteSpace(_displayText) ? Name : _displayText;
            set => _displayText = value;
        }
        public SilkFlo.Data.Core.Domain.Shop.Discount GetCore()
        {
            return _core;
        }
        public void SetCore(SilkFlo.Data.Core.Domain.Shop.Discount core)
        {
            _core = core;
        }

        public bool IsNew => string.IsNullOrWhiteSpace(Id);

        /// <summary>
        /// Primary Key
        /// </summary>
        #region Id
        [StringLength(255,
                      MinimumLength = 0,
                      ErrorMessage = "Id cannot be greater than 255 characters in length.")]
        [DisplayName("Id")]
        public string Id
        {
            get => _core.Id;
            set
            {
                if (_core.Id == value)
                    return;

                _core.Id = value;
            }
        }

        public string Id_Error { get; set; }
        public string Id_ErrorMessage { get; set; } = "Required";
        public bool Id_IsInValid { get; set; }
        #endregion

        #region Description Referrer
        [StringLength(100,
                      MinimumLength = 0,
                      ErrorMessage = "Description Referrer cannot be greater than 100 characters in length.")]
        [DisplayName("Description Referrer")]
        public string DescriptionReferrer
        {
            get => _core.DescriptionReferrer;
            set
            {
                if (_core.DescriptionReferrer == value)
                    return;

                _core.DescriptionReferrer = value;
            }
        }

        public string DescriptionReferrer_ErrorMessage { get; set; }
        public bool DescriptionReferrer_IsInValid { get; set; }
        #endregion

        #region Description Reseller
        [StringLength(100,
                      MinimumLength = 0,
                      ErrorMessage = "Description Reseller cannot be greater than 100 characters in length.")]
        [DisplayName("Description Reseller")]
        public string DescriptionReseller
        {
            get => _core.DescriptionReseller;
            set
            {
                if (_core.DescriptionReseller == value)
                    return;

                _core.DescriptionReseller = value;
            }
        }

        public string DescriptionReseller_ErrorMessage { get; set; }
        public bool DescriptionReseller_IsInValid { get; set; }
        #endregion

        #region Max
        [DisplayName("Max")]
        public int? Max
        {
            get => _core.Max;
            set
            {
                if (_core.Max == value)
                    return;

                _core.Max = value;
            }
        }

        public string Max_ErrorMessage { get; set; }
        public bool Max_IsInValid { get; set; }
        #endregion

        #region Min
        [DisplayName("Min")]
        public int? Min
        {
            get => _core.Min;
            set
            {
                if (_core.Min == value)
                    return;

                _core.Min = value;
            }
        }

        public string Min_ErrorMessage { get; set; }
        public bool Min_IsInValid { get; set; }
        #endregion

        #region Name
        [Required]
        [StringLength(100,
                      ErrorMessage = "Name must be between 1 and 100 characters in length.")]
        [DisplayName("Name")]
        public string Name
        {
            get => _core.Name;
            set
            {
                if (_core.Name == value)
                    return;

                _core.Name = value;
            }
        }

        public string Name_ErrorMessage { get; set; } = "Required";
        public bool Name_IsInValid { get; set; }
        #endregion

        #region Percent Referrer
        [DisplayName("Percent Referrer")]
        public int? PercentReferrer
        {
            get => _core.PercentReferrer;
            set
            {
                if (_core.PercentReferrer == value)
                    return;

                _core.PercentReferrer = value;
            }
        }

        public string PercentReferrer_ErrorMessage { get; set; }
        public bool PercentReferrer_IsInValid { get; set; }
        #endregion

        #region Percent Reseller
        [DisplayName("Percent Reseller")]
        public int? PercentReseller
        {
            get => _core.PercentReseller;
            set
            {
                if (_core.PercentReseller == value)
                    return;

                _core.PercentReseller = value;
            }
        }

        public string PercentReseller_ErrorMessage { get; set; }
        public bool PercentReseller_IsInValid { get; set; }
        #endregion

        private List<Models.Business.Client> _clients; 
        public List<Models.Business.Client> Clients 
        {
            get
            {
                if (_clients != null)
                    return _clients;

                _clients = new List<Business.Client>();

                if (_core.Clients == null)
                    return _clients;

                foreach (var core in _core.Clients)
                    _clients.Add(new Models.Business.Client(core));

                return _clients;
            }
            set => _clients = value;
        }

        private List<Models.Shop.Subscription> _subscriptions; 
        public List<Models.Shop.Subscription> Subscriptions 
        {
            get
            {
                if (_subscriptions != null)
                    return _subscriptions;

                _subscriptions = new List<Shop.Subscription>();

                if (_core.Subscriptions == null)
                    return _subscriptions;

                foreach (var core in _core.Subscriptions)
                    _subscriptions.Add(new Models.Shop.Subscription(core));

                return _subscriptions;
            }
            set => _subscriptions = value;
        }

        #region OwnerId
        public string OwnerId => UpdatedById ?? CreatedById;
        #endregion

        #region Owner  
        public string Owner => UpdatedBy ?? CreatedBy;
        #endregion
        

        #region CreatedBy
        [DisplayName("Created By")]
        public string CreatedBy => _core.CreatedBy == null ? "" : _core.CreatedBy.ToString();
        #endregion

        #region CreatedDate
        [DisplayName("Created Date")]
        public DateTime? CreatedDate
        {
            get => _core.CreatedDate;
            set
            {
                if (_core.CreatedDate == value)
                    return;

                _core.CreatedDate = value;
            }
        }
        #endregion

        [DisplayName("Created Date")]
        public string CreatedDateString => CreatedDate?.ToString(Data.Core.Settings.DateFormatShort);

        #region CreatedById
        [DisplayName("Created By Id")]
        public string CreatedById
        {
            get => _core.CreatedById;
            set => _core.CreatedById = value;
        }
        #endregion

        #region UpdatedById
        [DisplayName("Updated By Id")]
        public string UpdatedById
        {
            get => _core.UpdatedById;
            set => _core.UpdatedById = value;
        }
        #endregion

        #region UpdatedBy
        [DisplayName("Updated By")]
        public string UpdatedBy => _core.UpdatedBy == null ? "" : _core.UpdatedBy.ToString();
        #endregion

        #region UpdatedDate
        [DisplayName("Updated Date")]
        public DateTime? UpdatedDate
        {
            get => _core.UpdatedDate;
            set
            {
                if (_core.UpdatedDate == value)
                    return;

                _core.UpdatedDate = value;
            }
        }
        #endregion

        [DisplayName("Updated Date")]
        public string UpdatedDateString => UpdatedDate?.ToString(Data.Core.Settings.DateTimeFormatShort);


        [DisplayName("Date")]
        public string DateDisplayed => UpdatedDate == null ? CreatedDate?.ToString("yyyy-MM-dd") : UpdatedDate?.ToString("yyyy-MM-dd");

        [DisplayName("Date Time")]
        public string DateTimeDisplayed => UpdatedDate == null ? CreatedDate?.ToString("yyyy-MM-dd HH:mm:ss") : UpdatedDate?.ToString("yyyy-MM-dd HH:mm:ss");
        #endregion

        #region IsDeleted
        [DisplayName("Is Deleted")]
        public bool IsDeleted
        {
            get => _core.IsDeleted;
            set
            {
                if (_core.IsDeleted == value)
                    return;

                _core.IsDeleted = value;
            }
        }
        #endregion

        #region IsSaved
        [DisplayName("Is Saved")]
        public bool IsSaved => _core.IsSaved;
        #endregion

        public async Task GetCreatedAndUpdated(Data.Core.IUnitOfWork unitOfWork)
        {
            _core.CreatedBy = await unitOfWork.Users.GetAsync(_core.CreatedById);
            _core.UpdatedBy = await unitOfWork.Users.GetAsync(_core.UpdatedById);
        }

        /// <summary>
        /// Check unique key constraints.
        /// </summary>
        /// <returns>ViewModels.Feedback</returns>
        public async Task<ViewModels.Feedback> CheckUniqueAsync(
        Data.Core.IUnitOfWork unitOfWork,
        ViewModels.Feedback feedback)
        {
            if (unitOfWork == null)
                throw new NullReferenceException("Data.Core.IUnitOfWork cannot be null");

            // Check unique
            var message = await Data.Persistence.UnitOfWork.IsUniqueAsync(GetCore());// Data.Persistence.UnitOfWork.IsUniqueAsync(GetCore());

            if (string.IsNullOrWhiteSpace(message)) 
                return feedback;


             // We have a conflict, give feedback.
            if (feedback.Elements.ContainsKey("Name"))
                feedback.Elements["Name"] = message;
            else
                feedback.Elements.Add("Name", message);


            feedback.IsValid = false;

            return feedback;
        }

        public override string ToString()
        {
            if(!string.IsNullOrWhiteSpace(DisplayText))
                return DisplayText;

            return Name;
        }
        public static List<Models.Shop.Discount> Create(IEnumerable<Data.Core.Domain.Shop.Discount> cores, bool includeEmpty = false)
        {
            if (cores == null)
                return null;

            if(includeEmpty)
            {
                var models = new List<Models.Shop.Discount>();
                models.Add(new Models.Shop.Discount
                {
                    DisplayText = "<Empty>"
                });

                models.AddRange(cores.Select(core => new Models.Shop.Discount(core)));
                return models;
            }

            return cores.Select(core => new Models.Shop.Discount(core)).ToList();
        }

        public static Models.Shop.Discount[] Create(Data.Core.Domain.Shop.Discount[] cores, bool includeEmpty = false)
        {
            if (cores == null)
                return null;

            if(includeEmpty)
                return Create(cores.ToList(), true).ToArray();

            return cores.Select(core => new Models.Shop.Discount(core)).ToArray();
        }
    }
}